# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f581ec62b4ccf3a73e3ffced35e0c51424b883d15ae4a1d439cacbe0677cf6ca27dc925088a119a4ba5e37dff1b9d1f6fc3622ed108b7ef866a65abef00a6b29

test:
  secret_key_base: 14153677be7737a84c15cfbc4d39eb37b9852074b4b23f5ec8c541ae1928c9714dc7ae0a8d1203a5ea0fdb7d5ca7dbe4bf7054bbb45070d6dea0852b1a3a24ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
